# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cancer-proj',
                'doc_host': 'https://hamish-haggerty.github.io',
                'git_url': 'https://github.com/hamish-haggerty/cancer-proj',
                'lib_path': 'cancer_proj'},
  'syms': {'cancer_proj.core': {'cancer_proj.core.foo': ('core.html#foo', 'cancer_proj/core.py')}}}